apiVersion: v1
kind: ConfigMap
metadata:
  name: fowarder
data:
  fluentd.conf: |-

    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # Get the logs from the containers running in the cluster
    # This block parses logs using an expression valid for the Apache log format
    # Update this depending on your application log format
    @include k8s-fluentd.conf
    @include syslog-fluentd.conf
    @include aggregator-fluentd.conf
  
  k8s-fluentd.conf: |-
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /opt/bitnami/fluentd/logs/buffers/fluentd-docker.pos
      tag raw.kubernetes.*
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>
    <filter raw.kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>

  syslog-fluentd.conf: |-
    <source>
      @type tail
      read_from_head true
      path /var/lib/rancher/rke/log/*.log
      pos_file /opt/bitnami/fluentd/logs/buffers/fluentd-syslog.pos
      tag syslog.*
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>
    
  aggregator-fluentd.conf: |-
    <match **>
      @type forward
      <server>
        host fluentd-headless
        port 24224
      </server>

      tls_version TLSv1_2
      tls_insecure_mode true
      tls_verify_hostname false

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 5
        flush_interval 5s
      </buffer>
    </match>  