apiVersion: v2
appVersion: 211.1.1-E.1.0
dependencies:
- condition: global.fluentd.enabled
  name: fluentd
  repository: https://ifsclouddev.jfrog.io/artifactory/helm/
  version: 2.4.2
- condition: global.elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.9.2
- condition: global.kibana.enabled
  name: kibana
  repository: https://helm.elastic.co
  version: 7.9.2
description: k8s Demos
home: https://github.com/ifernando
kubeVersion: '>=1.18.0-0'
maintainers:
- email: roshane.ishara@gmail.com
  name: Mario Ishara Fernando
name: ifs-logging
version: 1.12.0
