{
 "title": "IFS Applications",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "customercode", "label": "Customer", "query": "label_values(customercode)" },
   { "name": "environmenttype", "label": "Environment", "query": "label_values(environmenttype)" }
  ]
 },
 "panels": [
  {
   "title": "Overall performance indication",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_sysload_report_generation{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{environmenttype}}"
    }
   ]
  },
  {
   "title": "Bachground jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_queue_ready{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "BG jobs Ready"
    },
    {
     "expr": "ifsamm_db_queue_wait{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "BG jobs Posted"
    },
    {
     "expr": "ifsamm_db_queue_exec{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "BG jobs Executing"
    },
    {
     "expr": "ifsamm_db_queue_error{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "BG jobs Errors"
    }
   ]
  },
  {
   "title": "Login test",
   "type": "stat",
   "description": "Known response codes:\n- 404, Main Server did not redirect to login page (deployment down?)\n- 500, Internal server error (database down?)\n- 503, MainServers not responding\n- 504, Gateway Error (a proxy is up, but ohs might be down?)\n- 996, Account used on other machine - license violation.\n- 997, IFS identity provider not responding\n- 998, URI not responding (proxy or ohs is down?)\n- 999, Server not reachable",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ifsamm_http_login{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Login resonse time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "ifsamm_http_login_duration{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Batch jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_server_proc_total{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "batch jobs total"
    },
    {
     "expr": "ifsamm_db_server_proc_broken{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "batch jobs broken"
    }
   ]
  },
  {
   "title": "B2B and B2E",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "ifsamm_http_response{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\", server=\"b2b10\"}",
     "legendFormat": "Apps10 - b2b"
    },
    {
     "expr": "ifsamm_http_response{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\", server=\"b2b9\"}",
     "legendFormat": "Apps9 - b2b"
    },
    {
     "expr": "ifsamm_http_response{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\", server=\"b2e9\"}",
     "legendFormat": "Apps9 - b2e"
    }
   ]
  },
  {
   "title": "PLAP ping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ifsamm_db_plsqlap_ping{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "PLAP ping"
    }
   ]
  },
  {
   "title": "Foundation Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "ifsamm_db_fnd_users{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Total fnd users (activated)"
    },
    {
     "expr": "ifsamm_db_logged_on_users{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "logged on fnd users"
    },
    {
     "expr": "ifsamm_db_roles_per_user{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Avg Roles per user "
    }
   ]
  },
  {
   "title": "Batch Message Queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_appl_messages_processing_2h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Processing > 2h"
    },
    {
     "expr": "ifsamm_db_appl_messages_released_2h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Released > 2h"
    },
    {
     "expr": "ifsamm_db_appl_messages_with_retries{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Retrying"
    },
    {
     "expr": "ifsamm_db_appl_server_bq_with_error{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Account password",
   "type": "stat",
   "description": "Is 0 if ifsmonitoring account returns 401 through MWS (not authorized) - All metric collection will be suspended until AMM service is restarted.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ifsamm_http_user_login{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "login"
    }
   ]
  },
  {
   "title": "State of DB",
   "type": "stat",
   "description": "State of DB, if installing all DB/APP metrics will stop collection.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "ifsamm_db_is_installing{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "login"
    }
   ]
  },
  {
   "title": "Cert expire on system url",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "ifsamm_http_cert{ifsrole=\"app\",customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Cleanup jobs",
   "type": "stat",
   "description": "Should never be less than 2\nlight and heavy cleanup jobs must be active",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "ifsamm_db_cleanup_total{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Cleanup jobs "
    }
   ]
  },
  {
   "title": "Application Search",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ifsamm_db_application_search_error{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "in error "
    },
    {
     "expr": "ifsamm_db_application_search_synch{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "to be synced"
    }
   ]
  },
  {
   "title": "Long running BG jobs",
   "type": "stat",
   "description": "BG jobs running more than 12h",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "ifsamm_db_deferred_jobs_executing_12h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Jobs running > 12h"
    }
   ]
  },
  {
   "title": "Background Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_batch_queue_active{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "active queues"
    },
    {
     "expr": "ifsamm_db_batch_queue_config{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "defined queues"
    },
    {
     "expr": "ifsamm_db_batch_queue_proc{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "sum of queue processes"
    },
    {
     "expr": "ifsamm_db_queue_processes{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "job_queue_prcesses"
    },
    {
     "expr": "ifsamm_db_stuck_batch_queue_processes{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "stuck jobs"
    }
   ]
  },
  {
   "title": "Objects not in Caches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "ifsamm_db_dictionary_refresh{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Dictionary"
    },
    {
     "expr": "ifsamm_db_reference_refresh{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Reference"
    },
    {
     "expr": "ifsamm_db_report_refresh{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Report"
    }
   ]
  },
  {
   "title": "Licenses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "ifsamm_db_license_limit{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Lincense limit"
    },
    {
     "expr": "ifsamm_db_users_left{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Users left on license"
    },
    {
     "expr": "ifsamm_db_days_left{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Days left on license"
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_connectivity_db_processes{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Queue processes that handle connectivity "
    },
    {
     "expr": "ifsamm_db_connectivity_inbox_routing{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Stuck inbox > 30m"
    },
    {
     "expr": "ifsamm_db_connectivity_outbox_routing{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Stuck outbox> 30m"
    },
    {
     "expr": "ifsamm_db_connectivity_processes{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Throughtput last 30m"
    }
   ]
  },
  {
   "title": "Print queue",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "ifsamm_db_printjob_failed_24h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "failed last 24h"
    },
    {
     "expr": "ifsamm_db_printjob_waiting_15m{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "waiting > 15m"
    },
    {
     "expr": "ifsamm_db_printjob_failed_24h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "failed last 24h"
    },
    {
     "expr": "ifsamm_db_printjob_working_2h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "working > 2h"
    }
   ]
  },
  {
   "title": "Print agents",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "ifsamm_db_printagents_remote_active{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "active print agents"
    },
    {
     "expr": "ifsamm_db_printjob_remotewaiting_15min{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "waiting >15m"
    },
    {
     "expr": "ifsamm_db_printjob_remotewaiting_30min{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "waiting >30min"
    }
   ]
  }
 ]
}