{
 "title": "IFS Cloud",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "customercode", "label": "Customer", "query": "label_values(customercode)" },
   { "name": "environmenttype", "label": "Environment", "query": "label_values(environmenttype)" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ifsamm_exporter_build_info{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Cert expire on system url",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifsamm_http_cert{ifsrole=\"app\",customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Days"
    }
   ]
  },
  {
   "title": "Foundation Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifsamm_db_fnd_users{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Total fnd users (activated)"
    },
    {
     "expr": "ifsamm_db_logged_on_users{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "logged on fnd users"
    },
    {
     "expr": "ifsamm_db_roles_per_user{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Avg Roles per user "
    }
   ]
  },
  {
   "title": "Background jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_queue_ready{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "BG jobs Ready"
    },
    {
     "expr": "ifsamm_db_queue_wait{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "BG jobs Posted"
    },
    {
     "expr": "ifsamm_db_queue_exec{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "BG jobs Executing"
    },
    {
     "expr": "ifsamm_db_queue_error{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "BG jobs Errors"
    }
   ]
  },
  {
   "title": "Objects not in Caches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifsamm_db_dictionary_refresh{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Dictionary"
    },
    {
     "expr": "ifsamm_db_reference_refresh{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Reference"
    },
    {
     "expr": "ifsamm_db_report_refresh{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Report"
    }
   ]
  },
  {
   "title": "Cleanup jobs",
   "type": "stat",
   "description": "Should never be less than 2\nlight and heavy cleanup jobs must be active",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifsamm_db_cleanup_total{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Cleanup jobs "
    }
   ]
  },
  {
   "title": "Long running BG jobs",
   "type": "stat",
   "description": "BG jobs running more than 12h",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ifsamm_db_deferred_jobs_executing_12h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Jobs running > 12h"
    }
   ]
  },
  {
   "title": "Batch jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_server_proc_total{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "batch jobs total"
    },
    {
     "expr": "ifsamm_db_server_proc_broken{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "batch jobs broken"
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_connectivity_db_processes{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Queue processes that handle connectivity "
    },
    {
     "expr": "ifsamm_db_connectivity_inbox_routing{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Stuck inbox > 30m"
    },
    {
     "expr": "ifsamm_db_connectivity_outbox_routing{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Stuck outbox> 30m"
    },
    {
     "expr": "ifsamm_db_connectivity_processes{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Throughtput last 30m"
    }
   ]
  },
  {
   "title": "Batch Message Queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_appl_messages_processing_2h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Processing > 2h"
    },
    {
     "expr": "ifsamm_db_appl_messages_released_2h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Released > 2h"
    },
    {
     "expr": "ifsamm_db_appl_messages_with_retries{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Retrying"
    },
    {
     "expr": "ifsamm_db_appl_server_bq_with_error{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Background Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifsamm_db_batch_queue_active{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "active queues"
    },
    {
     "expr": "ifsamm_db_batch_queue_config{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "defined queues"
    },
    {
     "expr": "ifsamm_db_batch_queue_proc{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "sum of queue processes"
    },
    {
     "expr": "ifsamm_db_queue_processes{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "job_queue_prcesses"
    },
    {
     "expr": "ifsamm_db_stuck_batch_queue_processes{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "stuck jobs"
    }
   ]
  },
  {
   "title": "Print queue",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifsamm_db_printjob_failed_24h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "failed last 24h"
    },
    {
     "expr": "ifsamm_db_printjob_waiting_15m{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "waiting > 15m"
    },
    {
     "expr": "ifsamm_db_printjob_failed_24h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "failed last 24h"
    },
    {
     "expr": "ifsamm_db_printjob_working_2h{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "working > 2h"
    }
   ]
  },
  {
   "title": "Print agents",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifsamm_db_printagents_remote_active{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "active print agents"
    },
    {
     "expr": "ifsamm_db_printjob_remotewaiting_15min{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "waiting >15m"
    },
    {
     "expr": "ifsamm_db_printjob_remotewaiting_30min{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "waiting >30min"
    }
   ]
  }
 ]
}