apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyn-class-gen-deployment
  labels:
    app: dyn-class-gen
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dyn-class-gen
  template:
    metadata:
      labels:
        app: dyn-class-gen
    spec:
      containers:
        - name: dyn-class-gen-container
          image: banzaicloud/dynclassgen:1.0
          env:
          - name: DYN_CLASS_COUNT
            value: "450"
          - name: MEM_USAGE_PER_OBJECT_MB
            value: "1"
          resources:
            requests:
              memory: "2Gi"
              cpu: 0.5
            limits:
              memory: "2Gi"
              cpu: 0.5
