apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "oracle-db-exporter.fullname" . }}
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include "oracle-db-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "oracle-db-exporter.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "oracle-db-exporter.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
      - name: {{ template "oracle-db-exporter.name" . }}
        ports:
        - containerPort: 9161
        image: {{ .Values.image.repository }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "oracle-db-exporter.fullname" . }}
              key: datasource
        - name: CUSTOM_METRICS
          value: /tmp/custom-metrics.toml
        volumeMounts:
          - name:  custom-metrics
            mountPath:  /tmp/custom-metrics.toml
            subPath: custom-metrics.toml
      volumes:
        - name: custom-metrics
          configMap:
            defaultMode: 420
            name: {{ template "oracle-db-exporter.fullname" . }}-custom-metrics
