{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "oracle-db-exporter.fullname" . }}
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include "oracle-db-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "oracle-db-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - "{{ .Values.namespace }}"
  endpoints:
  - port: "oracle-db-exporter"
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval | quote }}
    {{- end }}
    path: {{ .Values.serviceMonitor.path | quote }}
{{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- end }}
